---
- name: Play the template module
  hosts: localhost
  vars:
    env: "development"

  vars_files:
    - vars/{{ env }}.yaml

  tasks:
    - name: generation the hello_world.txt file
      template:
        src: hello_world.txt.j2
        dest: /tmp/hello_world.txt

    - name: show file context
      command: cat /tmp/hello_world.txt
      register: result

    - name: print stdout
      debug:
        msg: "{{ result.stdout_lines }}"
