---
- name: setup the nginx
  hosts: all
  become: true
  vars:
    username: "PinYi"
    mail: "880831ian@gmail.com"
    blog: "https://pin-yi.me"

  tasks:
    # 執行 'apt-get update' 指令。
    - name: update apt repo cache
      apt: name=nginx update_cache=yes

    # 執行 'apt-get install nginx' 指令。
    - name: install nginx with apt
      apt: name=nginx state=present

    # 於網頁根目錄 (DocumentRoot) 編輯 index.html。
    - name: modify index.html
      ansible.builtin.template: src=templates/index.html.j2
        dest=/var/www/html/index.html
        owner=www-data
        group=www-data
        mode="644"
        backup=yes
      notify: restart nginx

  # handlers
  #
  # * 當確認事件有被觸發才會動作。
  # * 一個 handler 可被多個 task 通知 (notify)，並於 tasks 跑完才會執行。
  handlers:
    # 執行 'sudo service nginx restart' 指令。
    - name: restart nginx
      service: name=nginx enabled=yes state=restarted

  # post_tasks:
  #
  # 在 tasks 之後執行的 tasks。
  post_tasks:
    # 檢查網頁內容。
    - name: review http state
      command: "curl -s http://localhost"
      register: web_context

    # 印出檢查結果。
    - name: print http state
      debug: msg={{ web_context.stdout_lines }}
